from flask import Flask
from typing import Any, Callable, Optional

def Swagger(app: Flask, template_file: Optional[str] = None) -> None: ...
def swag_from(file: str) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
