from typing import Any

class fields:
    @staticmethod
    def Int() -> Any: ...
    @staticmethod
    def Str(required: bool = False, location: str = "json") -> Any: ...
    @staticmethod
    def List(t: Any) -> Any: ...
