type Attribute {
  # the key is the table name followed by the column name delimited by a slash, eg table/col
  key: String!
  # json representation of the value
  value: String!
}

type Property {
  label: String!
  table: String!
  key: String!
}

input PropertyInput {
  label: String!
  table: String!
  key: String!
}

type EntityType {
  name: String!
  properties: [Property!]!
}

interface Entity {
  # this is the id of the entity in all tables it's associated with
  key: String!
  type: EntityType!
  properties (keys: [String!]): [Attribute!]
}

type Node implements Entity {
  key: String!
  type: EntityType!
  outgoing (limit: Int, offset: Int): EdgeList!
  incoming (limit: Int, offset: Int): EdgeList!
  properties (keys: [String!]): [Attribute!]
}

type Edge implements Entity {
  key: String!
  type: EntityType!
  source: Node!
  target: Node!
  properties (keys: [String!]): [Attribute!]
}

type Row {
  key: String!
  columns (keys: [String!]): [Attribute!]!
}

type NodeList {
  total: Int!
  data (offset: Int, limit: Int): [Node!]!
}

type EdgeList {
  total: Int!
  data (offset: Int, limit: Int): [Edge!]!
}

type RowList {
  total: Int!
  data (offset: Int, limit: Int): [Row!]!
}

type Table {
  name: String!
  primaryKey: String!
  # a list of key strings as they would appear in Attribute
  fields: [String!]!
  rows: RowList!
}

type Graph {
  name: String!
  nodeTypes: [EntityType!]!
  edgeTypes: [EntityType!]!
  nodes(nodeType: String, key: String, search: String): NodeList!
  edges: EdgeList!
}

type Workspace {
  name: String!
  tables: [Table!]!
  graphs: [Graph!]!
}

type Query {
  graph (workspace: String!, name: String!): Graph
  table (workspace: String!, name: String!): Table

  workspaces (name: String): [Workspace!]!
  graphs (workspace: String!, name: String): [Graph!]!
  tables (workspace: String!, name: String): [Table!]!
}

type Mutation {
  workspace (name: String!): String!
  deleteWorkspace (name: String!): String

  graph (workspace: String!, name: String!, node_tables: [String!]!, edge_table: String!): Graph
  table (workspace: String!, name: String!, edges: Boolean!, fields: [String!]!, primaryKey: String): Table!
}

schema {
  query: Query
  mutation: Mutation
}
