name: CI

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

jobs:
  build-and-test:
    name: Build and test on Ubuntu - Node 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'

      # Copy Env File
      - run: cp .env.default .env

      # Build and test Multinet server.
      - run: pip install pipenv
      - run: pipenv install --dev --deploy
      - run: pipenv run lint
      - run: pipenv run format
      - run: pipenv run typecheck
      - run: pipenv run test

      # Build and test Multinet client library.
      - run: cd multinetjs && yarn install
      - run: cd multinetjs && yarn build
      - run: cd multinetjs && yarn lint
      - run: cd multinetjs && yarn test

      # Build and test Multinet client app.
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: cp .env.test .env
      - run: cd client && yarn install
      - run: cd client && yarn lint
      - run: cd client && yarn lint:test
      - run: cd client && yarn test:server:up
      - run: cd client && yarn test:client:up
      - run: cd client && yarn test
      - run: cd client && yarn build
