# flake8: noqa

from typing import Dict, List, Any

from arango.collection import StandardCollection  # type: ignore
from arango.graph import Graph
from arango.aql import AQL  # type: ignore

class StandardDatabase:
    aql: AQL
    def has_database(self, name: str) -> bool: ...
    def has_graph(self, name: str) -> bool: ...
    def has_collection(self, name: str) -> bool: ...
    def create_database(self, name: str) -> bool: ...
    def create_collection(self, name: str, **kwargs: Any) -> StandardCollection: ...
    def create_graph(self, name: str, **kwargs: Any) -> Graph: ...
    def delete_database(self, name: str, **kwargs: Any) -> bool: ...
    def delete_collection(self, name: str, **kwargs: Any) -> bool: ...
    def delete_graph(self, name: str, **kwargs: Any) -> bool: ...
    def graph(self, name: str) -> Graph: ...
    def collection(self, name: str) -> StandardCollection: ...
    def collections(self) -> List[Dict]: ...
    def databases(self) -> List[str]: ...
    def graphs(self) -> List[Dict]: ...
