class DatabaseCreateError(Exception): ...
class EdgeDefinitionCreateError(Exception): ...
class AQLQueryValidateError(Exception): ...
class AQLQueryExecuteError(Exception): ...
class DocumentGetError(Exception): ...
