# flake8: noqa
from typing import Dict, List
from arango.collection import EdgeCollection, VertexCollection  # type: ignore

class Graph:
    def edge_collection(self, name: str) -> EdgeCollection: ...
    def vertex_collection(self, name: str) -> VertexCollection: ...
    def vertex_collections(self) -> List[str]: ...
    def edge_definitions(self) -> List[Dict]: ...
